/** 
	Generated by Helios3D
 */
function initHeliosSettings(  ) {
	settings.language = 'EN';
	hweSettings.latitude = 37.795;
	hweSettings.longitude = -122.394;
	hweSettings.timezone = '(GMT-08:00)';
	globals.qualitySetting = globals.quality.HIGH;
	hweSettings.use4PostRacks = true;
	hweSettings.numberOfTrees = 0;
	hweSettings.useAntialiasing = true;
	hweSettings.useFog = true;
	globals.collision.check = true;
	hweSettings.useTextureImages = false;
	settings.websocket.use = true;
	settings.analysis.active = true;
	settings.useRackOutput = false;
	settings.AnalysisHeightColor0 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor1 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor2 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor3 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor4 = new THREE.Vector4(0, 0, 0, 1);
	settings.websocket.sessionId = '63000760-f679-4d59-8218-85269110049a';
	settings.websocket.port = 80;
	settings.rackOutput.minPower = -1.0;
	settings.rackOutput.maxPower = -1.0;
	hweSettings.maxLoss = 1.0;
	settings.modules.fieldNumbersAvailable = true;
	hweSettings.performanceTimeSpan = 12;
	   settings.optimizedShadows = true;;
	   settings.sun.shadowCascadeCount = 3;;
	   settings.useShadowPlanes = false;;
}

var projectData = {
	"id": '46af131b-1841-4da9-b7a3-5aa338620872',
	"name": {
		"DE": 'Tano Project_Gyro',
		"EN": 'Tano Project_Gyro'
	},
	"position": {
		"DE": '37,795000 Lat -122,394000 Lng',
		"EN": '37.795000 Lat -122.394000 Long'
	},
	"power": {
		"DE": '34,961625 MWp',
		"EN": '34.961625 MWp'
	},
	"area": {
		"DE": '272.213,059',
		"EN": '272,213.059'
	},
	"tableCount": {
		"DE": '3453',
		"EN": '3453'
	},
	"moduleCount": {
		"DE": '86325',
		"EN": '86325'
	}
};
