/** 
	Generated by Helios3D
 */
window.hweDynamicLoading = {
	"loadDataDynamic": true,
	"main_terrain_files": ['js/terrain_data/mainTerrain0.js'],
	"inner_terrain_files": ['js/terrain_data/innerTerrain0.js'],
	"outer_terrain_files": ['js/terrain_data/outerTerrain0.js'],
	"additional_files": []
};
