/** 
	Generated by Helios3D
 */
function initHeliosSettings(  ) {
	settings.language = 'EN';
	hweSettings.latitude = 37.795;
	hweSettings.longitude = -122.394;
	hweSettings.timezone = '(GMT-08:00)';
	globals.qualitySetting = globals.quality.HIGH;
	hweSettings.use4PostRacks = true;
	hweSettings.numberOfTrees = 0;
	hweSettings.useAntialiasing = true;
	hweSettings.useFog = true;
	globals.collision.check = true;
	hweSettings.useTextureImages = false;
	settings.websocket.use = true;
	settings.analysis.active = true;
	settings.useRackOutput = false;
	settings.AnalysisHeightColor0 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor1 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor2 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor3 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor4 = new THREE.Vector4(0, 0, 0, 1);
	settings.websocket.sessionId = '1f70b9b0-8b13-47d4-a9d1-0b306d65e8d7';
	settings.websocket.port = 80;
	settings.rackOutput.minPower = -1.0;
	settings.rackOutput.maxPower = -1.0;
	hweSettings.maxLoss = 1.0;
	settings.modules.fieldNumbersAvailable = true;
	hweSettings.performanceTimeSpan = 12;
	   settings.optimizedShadows = true;;
	   settings.sun.shadowCascadeCount = 3;;
	   settings.useShadowPlanes = false;;
}

var projectData = {
	"id": '3b50a97b-d69b-4051-9842-4bbd2ee1a06f',
	"name": {
		"DE": 'Otake Project',
		"EN": 'Otake Project'
	},
	"position": {
		"DE": '37,795000 Lat -122,394000 Lng',
		"EN": '37.795000 Lat -122.394000 Long'
	},
	"power": {
		"DE": '27,165375 MWp',
		"EN": '27.165375 MWp'
	},
	"area": {
		"DE": '284.204,140',
		"EN": '284,204.140'
	},
	"tableCount": {
		"DE": '2683',
		"EN": '2683'
	},
	"moduleCount": {
		"DE": '67075',
		"EN": '67075'
	}
};
