/** 
	Generated by Helios3D
 */
window.hweDynamicLoading = {
	"loadDataDynamic": true,
	"main_terrain_files": ['js/terrain_data/mainTerrain0.js', 'js/terrain_data/mainTerrain1.js', 'js/terrain_data/mainTerrain2.js', 'js/terrain_data/mainTerrain3.js', 'js/terrain_data/mainTerrain4.js', 'js/terrain_data/mainTerrain5.js', 'js/terrain_data/mainTerrain6.js', 'js/terrain_data/mainTerrain7.js', 'js/terrain_data/mainTerrain8.js', 'js/terrain_data/mainTerrain9.js', 'js/terrain_data/mainTerrain10.js', 'js/terrain_data/mainTerrain11.js', 'js/terrain_data/mainTerrain12.js', 'js/terrain_data/mainTerrain13.js', 'js/terrain_data/mainTerrain14.js', 'js/terrain_data/mainTerrain15.js', 'js/terrain_data/mainTerrain16.js', 'js/terrain_data/mainTerrain17.js', 'js/terrain_data/mainTerrain18.js', 'js/terrain_data/mainTerrain19.js', 'js/terrain_data/mainTerrain20.js', 'js/terrain_data/mainTerrain21.js', 'js/terrain_data/mainTerrain22.js', 'js/terrain_data/mainTerrain23.js', 'js/terrain_data/mainTerrain24.js', 'js/terrain_data/mainTerrain25.js', 'js/terrain_data/mainTerrain26.js', 'js/terrain_data/mainTerrain27.js', 'js/terrain_data/mainTerrain28.js', 'js/terrain_data/mainTerrain29.js', 'js/terrain_data/mainTerrain30.js', 'js/terrain_data/mainTerrain31.js', 'js/terrain_data/mainTerrain32.js', 'js/terrain_data/mainTerrain33.js', 'js/terrain_data/mainTerrain34.js', 'js/terrain_data/mainTerrain35.js', 'js/terrain_data/mainTerrain36.js', 'js/terrain_data/mainTerrain37.js', 'js/terrain_data/mainTerrain38.js'],
	"inner_terrain_files": ['js/terrain_data/innerTerrain0.js'],
	"outer_terrain_files": ['js/terrain_data/outerTerrain0.js'],
	"additional_files": []
};
