/** 
	Generated by Helios3D
 */
function initHeliosSettings(  ) {
	settings.language = 'EN';
	hweSettings.latitude = 36.219;
	hweSettings.longitude = 139.371;
	hweSettings.timezone = '(GMT+09:00)';
	globals.qualitySetting = globals.quality.HIGH;
	hweSettings.use4PostRacks = true;
	hweSettings.numberOfTrees = 25000;
	hweSettings.useAntialiasing = true;
	hweSettings.useFog = true;
	globals.collision.check = true;
	hweSettings.useTextureImages = false;
	settings.websocket.use = true;
	settings.analysis.active = true;
	settings.useRackOutput = false;
	settings.AnalysisHeightColor0 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor1 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor2 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor3 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor4 = new THREE.Vector4(0, 0, 0, 1);
	settings.websocket.sessionId = '382f5337-40cc-4ea6-887a-4aec2ca7e0af';
	settings.websocket.port = 80;
	settings.rackOutput.minPower = -1.0;
	settings.rackOutput.maxPower = -1.0;
	hweSettings.maxLoss = 1.0;
	settings.modules.fieldNumbersAvailable = true;
	hweSettings.performanceTimeSpan = 12;
	   settings.optimizedShadows = true;;
	   settings.sun.shadowCascadeCount = 3;;
	   settings.useShadowPlanes = false;;
}

var projectData = {
	"id": '5c7abe25-c679-40ac-9776-ca754a6c0239',
	"name": {
		"DE": 'Sukagawa Project',
		"EN": 'Sukagawa Project'
	},
	"position": {
		"DE": '36,219001 Lat 139,370605 Lng',
		"EN": '36.219001 Lat 139.370605 Long'
	},
	"power": {
		"DE": '31,944375 MWp',
		"EN": '31.944375 MWp'
	},
	"area": {
		"DE": '205.136,687',
		"EN": '205,136.687'
	},
	"tableCount": {
		"DE": '3155',
		"EN": '3155'
	},
	"moduleCount": {
		"DE": '78875',
		"EN": '78875'
	}
};
