/** 
	Generated by Helios3D
 */
function initHeliosSettings(  ) {
	settings.language = 'EN';
	hweSettings.latitude = 37.795;
	hweSettings.longitude = -122.394;
	hweSettings.timezone = '(GMT-08:00)';
	globals.qualitySetting = globals.quality.HIGH;
	hweSettings.use4PostRacks = true;
	hweSettings.numberOfTrees = 0;
	hweSettings.useAntialiasing = true;
	hweSettings.useFog = true;
	globals.collision.check = true;
	hweSettings.useTextureImages = false;
	settings.websocket.use = true;
	settings.analysis.active = true;
	settings.useRackOutput = false;
	settings.AnalysisHeightColor0 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor1 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor2 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor3 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor4 = new THREE.Vector4(0, 0, 0, 1);
	settings.websocket.sessionId = 'a73d286f-d10e-4c91-a14a-667853bedcaf';
	settings.websocket.port = 80;
	settings.rackOutput.minPower = -1.0;
	settings.rackOutput.maxPower = -1.0;
	hweSettings.maxLoss = 1.0;
	settings.modules.fieldNumbersAvailable = true;
	hweSettings.performanceTimeSpan = 12;
	   settings.optimizedShadows = true;;
	   settings.sun.shadowCascadeCount = 3;;
	   settings.useShadowPlanes = false;;
}

var projectData = {
	"id": '2cc0ad49-3a17-4868-a08c-ac3a6ccb5c8c',
	"name": {
		"DE": 'Aomori Project',
		"EN": 'Aomori Project'
	},
	"position": {
		"DE": '37,795000 Lat -122,394000 Lng',
		"EN": '37.795000 Lat -122.394000 Long'
	},
	"power": {
		"DE": '70,010000 MWp',
		"EN": '70.010000 MWp'
	},
	"area": {
		"DE": '503.059,359',
		"EN": '503,059.359'
	},
	"tableCount": {
		"DE": '7001',
		"EN": '7001'
	},
	"moduleCount": {
		"DE": '175025',
		"EN": '175025'
	}
};
