/** 
	Generated by Helios3D
 */
function getRackDataDefinitions( baseTexture ) {
	return [{
			"name": '5x5_JS-Mono_400W',
			"length": 10140.0,
			"width": 5140.0,
			"height": 1500.0,
			"rows": 5,
			"columns": 5,
			"orientation": 'Horizontal',
			"mirrored": false,
			"modelGeometry": null,
			"texture": baseTexture[0],
			"isTracker": false,
			"maxInclinationAngle": 0.524,
			"usePostData": true,
			"rackPostData": ['rackPosts0'],
			"rackInsertions": ['getRacks0']
		}];
;
}
