/** 
	Generated by Helios3D
 */
function initHeliosSettings(  ) {
	settings.language = 'EN';
	hweSettings.latitude = 35.678;
	hweSettings.longitude = 139.839;
	hweSettings.timezone = '(GMT+09:00)';
	globals.qualitySetting = globals.quality.MEDIUM;
	hweSettings.use4PostRacks = false;
	hweSettings.numberOfTrees = 100000;
	hweSettings.useAntialiasing = true;
	hweSettings.useFog = true;
	globals.collision.check = true;
	hweSettings.useTextureImages = false;
	settings.websocket.use = true;
	settings.analysis.active = true;
	settings.useRackOutput = false;
	settings.AnalysisHeightColor0 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor1 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor2 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor3 = new THREE.Vector4(0, 0, 0, 0);
	settings.AnalysisHeightColor4 = new THREE.Vector4(0, 0, 0, 1);
	settings.websocket.sessionId = 'e1d1662e-0cfc-4532-af47-4724e70befab';
	settings.websocket.port = 32256;
	settings.rackOutput.minPower = -1.0;
	settings.rackOutput.maxPower = -1.0;
	hweSettings.maxLoss = 1.0;
	settings.modules.fieldNumbersAvailable = true;
	hweSettings.performanceTimeSpan = 12;
	   settings.optimizedShadows = true;;
	   settings.sun.shadowCascadeCount = 3;;
	   settings.useShadowPlanes = false;;
}

var projectData = {
	"id": '1bb6a5a7-1e4e-4d15-a0c9-e0f3e8b2d79b',
	"name": {
		"DE": 'Kamogawa',
		"EN": 'Kamogawa'
	},
	"position": {
		"DE": '35,678000 Lat 139,839303 Lng',
		"EN": '35.678000 Lat 139.839303 Long'
	},
	"power": {
		"DE": '139,523000 MWp',
		"EN": '139.523000 MWp'
	},
	"area": {
		"DE": '1.195.397,195',
		"EN": '1,195,397.195'
	},
	"tableCount": {
		"DE": '16810',
		"EN": '16810'
	},
	"moduleCount": {
		"DE": '336200',
		"EN": '336200'
	}
};
