/** 
	Generated by Helios3D
 */
function getRackDataDefinitions( baseTexture ) {
	return [{
			"name": 'CS3W415 Hiku 4x5 Landscape ',
			"length": 10640.0,
			"width": 4267.0,
			"height": 500.0,
			"rows": 4,
			"columns": 5,
			"orientation": 'Horizontal',
			"mirrored": false,
			"modelGeometry": null,
			"texture": baseTexture[0],
			"isTracker": false,
			"maxInclinationAngle": 0.698,
			"usePostData": true,
			"rackPostData": ['rackPosts0'],
			"rackInsertions": ['getRacks0']
		}];
;
}
